language: java
jdk:
 - oraclejdk7
addons:
  firefox: "23.0.1"
before_install:
 - jboss-as-conf/setup.sh
 - chmod +x jboss-as-7.1.1.Final/bin/standalone.sh
install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script: true
script:
 - mvn -f aerogear-rest-service/pom.xml package
 - mv aerogear-rest-service/target/aerogear-rest-service.war jboss-as-7.1.1.Final/standalone/deployments
 - ./jboss-as-7.1.1.Final/bin/standalone.sh &
 - mvn -f aerogear-js-qunit-cors-jsonp-tests/pom.xml test
